---

- include: pb.init.make_clean.yaml

############################################################
- name: Create and apply configuration for Leaf QFX / L2
  hosts: leaf-qfx-l2
  connection: local
  gather_facts: no
  pre_tasks:
    - include_vars: "{{ topology_file }}"
  roles:
    - common
    - underlay-ebgp
    - overlay-evpn-qfx-l2
    - overlay-evpn-access
    - build-config

############################################################
- name: Create and apply configuration for Leaf QFX / L3
  hosts: leaf-qfx-l3
  connection: local
  gather_facts: no
  pre_tasks:
    - include_vars: "{{ topology_file }}"
  roles:
    - common
    - underlay-ebgp
    - overlay-evpn-qfx-l3
    - overlay-evpn-access
    - build-config

############################################################
- name: Create and apply configuration for Spines / MX
  hosts: spine-mx
  connection: local
  gather_facts: no
  pre_tasks:
    - include_vars: "{{ topology_file }}"
  roles:
    - common
    - underlay-ebgp
    - overlay-evpn-mx-l3
    - build-config

############################################################
- name: Create and apply configuration for Spines / QFX
  hosts: spine-qfx
  connection: local
  gather_facts: no
  pre_tasks:
    - include_vars: "{{ topology_file }}"
  roles:
    - common
    - underlay-ebgp
    - overlay-evpn-qfx-l3
    - build-config

############################################################
- name: Create and apply configuration for Fabric
  hosts: fabric
  connection: local
  gather_facts: no
  pre_tasks:
    - include_vars: "{{ topology_file }}"
  roles:
    - common
    - underlay-ebgp
    - build-config
