---
- name: junos_facts module
  hosts: spine,leaf
  connection: local
  gather_facts: no
  vars:
    credentials:
      host: "{{ ansible_ssh_host }}"
      port: "{{ netconf_port }}"
      username: "{{ ansible_ssh_user }}"
      password: "{{ ansible_ssh_pass }}"
  tasks:
    - name: Collect device Facts
      junos_facts:
        config: no
        provider: "{{ credentials }}"
      register: result

    - debug: var=result
