---
- name: Delete FQDN files
  connection: local
  hosts: leaf,spine,fabric,server
  gather_facts: no
  pre_tasks:
    - include_vars: "{{ topology_file }}"
  tasks:
    - name: Delete FQDN files
      file:
        path: "host_vars/{{ inventory_hostname}}/fqdn.yaml"
        state: absent
