
access:
    interfaces:
        -   name: "{{ topo[inventory_hostname].port3.name }}"
            description: "{{ topo[inventory_hostname].port3.peer }}"
            mode: access
            vlans: [ 105 ]
        -   name: "{{ topo[inventory_hostname].port4.name }}"
            description: "{{ topo[inventory_hostname].port4.peer }}"
            vlans: [ 101, 102, 103, 104, 105, 106, 107, 108 ]
            mode: aggregate
            parent: ae0
            
        -   name: ae0
            mode: trunk
            esi: 00:01:01:01:01:01:01:01:01:01
            vlans: [ 101, 102, 103, 104, 105, 106, 107, 108 ]
            lacp_system_id: 00:00:00:01:01:01
            lacp_mode: active
            description: "customer XX - server YY"

